<?php
require_once "app/views/templates/layout/header.phtml";
?>

<main class="home">
    <div class="home__card home__card--genres">
      <h2 class="home__card-title">
        <a href="<?= !empty($_SESSION['id']) ? 'admin/generos' : 'generos' ?>">Generos</a>
      </h2>
    </div>
    <div class="home__card home__card--books">
      <h2 class="home__card-title">
        <a href="<?= !empty($_SESSION['id']) ? 'admin/libros' : 'libros' ?>">Libros</a>
      </h2>
    </div>
</main>

<?php
require_once 'app/views/templates/layout/footer.phtml';
?>
